### ISSUE TITLE
BCD-SYS with .WIM files

### ISSUE THREAD

**Issue by scorchpc** [jpz4085/BCD-SYS#1]
Hi,

I am trying to use your scripts in conjunction with .WIM images. 

If possible, I would like to discuss this with you. 

Let me know. Thanks!

**Comment by jpz4085** [comment]
> Hi,
> 
> I am trying to use your scripts in conjunction with .WIM images.
> 
> If possible, I would like to discuss this with you.
> 
> Let me know. Thanks!

Sure, I'd be glad to help. Please describe in detail what you are attempting to do and exactly what is happening.

**Comment by scorchpc** [comment]
We have a customer with a bunch of Windows PE images that use .WIM files. 

We would like to replace this with a Linux solution. 

We can use wimapply to install the partitions, but then the drive won't boot. Presumably we need to do a bcdedit in Windows, which is what led me to your bcd-sys.sh script. Your script looks promising!  But when we tried it, we still couldn't get it to work, I think because we didn't use your scripts properly. 

If possible, I could setup a session with you. Or let me know what you think. Thanks!

**Comment by jpz4085** [comment]
> We have a customer with a bunch of Windows PE images that use .WIM files.
> 
> We would like to replace this with a Linux solution.

I assume the current situation involves booting to a WinPE environment, partitioning and formatting the disk then applying a WIM image and making it bootable. If so then Linux with the wimtools and BCD-SYS (with its own requirements installed) should be able to do the same job.
 
> We can use wimapply to install the partitions, but then the drive won't boot. Presumably we need to do a bcdedit in Windows, which is what led me to your bcd-sys.sh script. Your script looks promising! But when we tried it, we still couldn't get it to work, I think because we didn't use your scripts properly.

For reference an overview of the Windows imaging/installation process from Linux would be as follows:

1. Partition the target disk using fdisk or gdisk and create any EFI or System Reserved and recovery partitions needed. Scripts could be used for automation and standardization.
2. Format partitions with the appropriate file system. Usually FAT32 for EFI but NTFS for everything else.
3. Use wimapply to write the image to the block device of the Windows partition.
4. Mount the Windows partition and pass the mount path to the script with any other options if needed. This step is similar to using bcdboot.
5. Boot from the target disk and proceed from there.

This is the procedure I used successfully when developing and testing the scripts.

> If possible, I could setup a session with you. Or let me know what you think. Thanks!

That's fine. Let me know how you want to proceed if we need to get more in depth.

**Comment by scorchpc** [comment]
We were able to get your scripts working. Thanks for your help sir!

**Comment by jpz4085** [comment]
> We were able to get your scripts working. Thanks for your help sir!

You're welcome!
