### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by urzparat** [jpz4085/BCD-SYS#2]
Awesome work, thank you! But there are some things I would like to change (and eventually pitch it to you). Would you care to add a license to your code?

**Comment by jpz4085** [comment]
> Awesome work, thank you! But there are some things I would like to change (and eventually pitch it to you). Would you care to add a license to your code?

Sure, I'm open to changes and suggestions. Yeah, I should add a license (GPL v3) when I make some more commits in the near future. Glad you find it useful!

**Comment by urzparat** [comment]
@jpz4085 Thank you for adding those licenses! 

~So I know it might be a bit rude to ask, but do you know how to boot into a WinPE via a `boot.wim` directly without applying it? I've read through a ton of `reboot.pro`-Threads and other related content but never was able to get it right. I know that with PXE+wimboot this is possible. But I want to create a `boot.wim` from within Linux with `wimtools` and then create a BCD in the EFI-Partition to boot it directly.~ I just needed to take the `boot.sdi` from the created WIM-Files (with `copype.cmd amd64 C:\...`) in `media\boot\boot.sdi` :man_facepalming:
