### ISSUE TITLE
some minors errors with flash devices like /dev/nvme0n1  

### ISSUE THREAD

**Issue by dash1540** [jpz4085/BCD-SYS#3]
i got some errors when run: bcd-sys -v /mnt/windows
where /mnt/windows is mount point to /dev/nvme0n1p3 (win part) and EFI part /dev/nvme0n1p1

DEBUG: Length=3, String=MUI
DEBUG: Length=11, String=BOOTMGR.XSL
DEBUG: Length=3, String=MUI
DEBUG: Length=11, String=BOOTMGR.XSL
sfdisk: cannot open /dev/nvme0n1p: No such file or directory
Update main BCD hive with new entries...
Loader GUID: {005a0c6e-67ad-4e92-99e9-a0546faf8732}
Resume GUID: {71992148-7aca-4e78-afc5-4742c3e3e41f}
sfdisk: cannot open /dev/nvme0n1p: No such file or directory
sfdisk: cannot open /dev/nvme0n1p: No such file or directory
sfdisk: cannot open /dev/nvme0n1p: No such file or directory
sfdisk: cannot open /dev/nvme0n1p: No such file or directory
Update recovery BCD hive with new entries...
Clean up temporary files...
Finished configuring UEFI boot files.

error is "/dev/nvme0n1p", should be "/dev/nvme0n1".
probably same with device /dev/mmcblk0

**Comment by jpz4085** [comment]
> error is "/dev/nvme0n1p", should be "/dev/nvme0n1".
> probably same with device /dev/mmcblk0

OK, I've updated the Linux scripts to remove the trailing letter "p" which should fix the issue. Let me know how it goes.

**Comment by dash1540** [comment]
Yes now is working, no errors messages and can mbr/uefi boot sda/nvme0n1, nice work and thanks, BCD-SYS is the first tool to create BCD store from linux/macos, I hope we will have the same thing with wimlib something like dism /add-driver.

**Comment by jpz4085** [comment]
You're welcome!
