### ISSUE TITLE
BCD Error - Windows Failed to Start

### ISSUE THREAD

**Issue by scorchpc** [jpz4085/BCD-SYS#4]
Hello,

We received the attached error after doing this script. This is a Windows 10 (build 17763).  

![BCD-Error-20240508](https://github.com/jpz4085/BCD-SYS/assets/11061645/abb6ed09-a9ac-450c-95d3-01e117672b12)

Here is the log from this:

Get block device for mount point (sudo required later)...
/root/.hivexsh: Read-only file system
Remove entry at {cf4ca6b0-57e3-46f1-85ed-e8a96bd010e6}
/root/.hivexsh: Read-only file system
/root/.hivexsh: Read-only file system
Remove {cf4ca6b0-57e3-46f1-85ed-e8a96bd010e6} from WBM display order.
/root/.hivexsh: Read-only file system
/root/.hivexsh: Read-only file system
Remove entry at {d32da8ce-d3d7-4017-a889-79e9afc61bcf}
/root/.hivexsh: Read-only file system
/root/.hivexsh: Read-only file system
/root/.hivexsh: Read-only file system
Remove {d32da8ce-d3d7-4017-a889-79e9afc61bcf} from WBM resume object.
/root/.hivexsh: Read-only file system
Update main BCD hive with new entries...
/root/.hivexsh: Read-only file system
Loader GUID: {f697c3eb-534d-41f1-b3c4-816ccbf55481}
Resume GUID: {6371cb56-ea7f-4867-99a2-02d97ab025f9}
/root/.hivexsh: Read-only file system
/root/.hivexsh: Read-only file system
/root/.hivexsh: Read-only file system
Update recovery BCD hive with new entries...
/root/.hivexsh: Read-only file system
/root/.hivexsh: Read-only file system
Clean up temporary files...
Finished configuring UEFI boot files.

And here is the XML:

<WIM>
	<TOTALBYTES>15371843041</TOTALBYTES>
	<IMAGE INDEX="1">
		<DIRCOUNT>109262</DIRCOUNT>
		<FILECOUNT>335963</FILECOUNT>
		<TOTALBYTES>41920901581</TOTALBYTES>
		<HARDLINKBYTES>7696989766</HARDLINKBYTES>
		<CREATIONTIME>
			<HIGHPART>0x01D8B2A8</HIGHPART>
			<LOWPART>0x8818FD5F</LOWPART>
		</CREATIONTIME>
		<LASTMODIFICATIONTIME>
			<HIGHPART>0x01D8B2A8</HIGHPART>
			<LOWPART>0x9C39C2D5</LOWPART>
		</LASTMODIFICATIONTIME>
		<WIMBOOT>0</WIMBOOT>
		<WINDOWS>
			<ARCH>9</ARCH>
			<PRODUCTNAME>Microsoft® Windows® Operating System</PRODUCTNAME>
			<EDITIONID>EnterpriseS</EDITIONID>
			<INSTALLATIONTYPE>Client</INSTALLATIONTYPE>
			<SERVICINGDATA>
				<GDRDUREVISION>0</GDRDUREVISION>
				<PKEYCONFIGVERSION>10.0.17763.2989;2016-01-01T00:00:00Z</PKEYCONFIGVERSION>
				<IMAGESTATE>IMAGE_STATE_COMPLETE</IMAGESTATE>
			</SERVICINGDATA>
			<HAL>acpiapic</HAL>
			<PRODUCTTYPE>WinNT</PRODUCTTYPE>
			<PRODUCTSUITE>Terminal Server</PRODUCTSUITE>
			<LANGUAGES>
				<LANGUAGE>en-US</LANGUAGE>
				<DEFAULT>en-US</DEFAULT>
			</LANGUAGES>
			<VERSION>
				<MAJOR>10</MAJOR>
				<MINOR>0</MINOR>
				<BUILD>17763</BUILD>
				<SPBUILD>3287</SPBUILD>
				<SPLEVEL>0</SPLEVEL>
			</VERSION>
			<SYSTEMROOT>WINDOWS</SYSTEMROOT>
		</WINDOWS>
		<NAME>Factory_0</NAME>
	</IMAGE>
	<IMAGE INDEX="2">
		<DIRCOUNT>1</DIRCOUNT>
		<FILECOUNT>0</FILECOUNT>
		<TOTALBYTES>0</TOTALBYTES>
		<HARDLINKBYTES>0</HARDLINKBYTES>
		<CREATIONTIME>
			<HIGHPART>0x01D8B2A8</HIGHPART>
			<LOWPART>0x98BDFB35</LOWPART>
		</CREATIONTIME>
		<LASTMODIFICATIONTIME>
			<HIGHPART>0x01D8B2A8</HIGHPART>
			<LOWPART>0x9C3C254D</LOWPART>
		</LASTMODIFICATIONTIME>
		<WIMBOOT>0</WIMBOOT>
		<NAME>Factory_1</NAME>
	</IMAGE>
	<RadiantImageData Version="1">
		<Slot Name="Factory">
			<ExtendedInfo>20-58977715</ExtendedInfo>
			<EmbeddedOsType>0</EmbeddedOsType>
			<DateTimeCreated>
				<Day>17</Day>
				<Month>8</Month>
				<Year>2022</Year>
				<Hour>15</Hour>
				<Minute>16</Minute>
			</DateTimeCreated>
			<VolumeList>
				<Volume>
					<Index>2</Index>
					<Active>0</Active>
					<WinRE>0</WinRE>
					<SizeBytes>99970187264</SizeBytes>
					<FileSystem>NTFS</FileSystem>
					<ImageName>Factory_0</ImageName>
					<VolumeLabel>OS</VolumeLabel>
					<BootSector></BootSector>
					<BootSectType>2</BootSectType>
				</Volume>
				<Volume>
					<Index>3</Index>
					<Active>0</Active>
					<WinRE>0</WinRE>
					<SizeBytes>4923064320</SizeBytes>
					<FileSystem>NTFS</FileSystem>
					<ImageName>Factory_1</ImageName>
					<VolumeLabel>Imaging</VolumeLabel>
					<BootSector></BootSector>
					<BootSectType>2</BootSectType>
				</Volume>
			</VolumeList>
		</Slot>
		<ImagingSuiteVersion>
			<Major>5</Major>
			<Minor>3</Minor>
			<Build>0</Build>
			<Patch>6</Patch>
		</ImagingSuiteVersion>
	</RadiantImageData>
</WIM>

Let me know any feedback or needs.

Thanks!

**Comment by scorchpc** [comment]
The XML did not paste well, but let me know any needs. Thanks again!

**Comment by jpz4085** [comment]
> We received the attached error after doing this script. This is a Windows 10 (build 17763).

The script didn't build the BCD successfully which is the cause of the error in the screenshot.

> /root/.hivexsh: Read-only file system

This error seems to indicate that the Linux partition, or at least the folder the scripts are running in, is not writable for some reason. Or there is a permissions issue. The tool needs to build temporary hivexsh scripts for the Windows entries. As a result hivexsh created invalid entries when updating the BCD in the system partition.

Can you provide some detail on the Linux environment used in this case? Is it a local installation on a workstation or a live USB drive? It appears the utility is being run from the root user profile folder.

**Comment by scorchpc** [comment]
Here is the feedback I received:

The read-only message looks like an issue, but it isn't.  That is the 'hivexsh' command complaining about not being able to write to its history file, which isn't required for it to work.  The bcd-sys script uses the 'hivexsh' command, hence the complaints.  The temporary hivexsh scripts generated by the bcd-sys command are being created under /tmp which is read-write.

**Comment by scorchpc** [comment]
We have also done this process successfully in the same environment, with a different WIM / PC

Therefore, we don't think the read-only is the issue

**Comment by jpz4085** [comment]
> We have also done this process successfully in the same environment, with a different WIM / PC
> 
> Therefore, we don't think the read-only is the issue

OK, understood. Provide as much detail as possible (or can obtain via feedback) describing the difference between the last success and the current failure. We need to determine what changed to track down the cause.

- Were the same, different or no warnings/errors produced by the script when it was successful?
- What Linux distribution, version and installation/configuration was used in both instances?
- Where different Linux systems/environments used or the same one with the same user account?
- Is the script being run from a local copy of the repo or installed to the system?
- What options were used with the script in both instances?
- What Windows version was applied to the systems in each case?

If possible attach a copy of the Recovery BCD file referenced in the screenshot so I can examine the contents.

**Comment by scorchpc** [comment]
Here is a zip with the BCD file you asked for:

[BCD.zip](https://github.com/jpz4085/BCD-SYS/files/15265109/BCD.zip)

Here is "uname -a" from the environment:

Linux minion 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
 This is Debian Bookworm

On the successful script, we also had the read only errors, but as mentioned that was just for writing a history file. The successful image was for:
System Root:            WINDOWS
Major Version:          10
Minor Version:          0
Build:                  14393

Same Linux environment and user (root). 

The script is installed to the system.  Both invocations used:
bcd-sys <win_mnt> -s <esp_mnt>


For the issue, this WIM is a Windows 10 (build 17763)

Let me know any questions.

Thanks again for the help!

**Comment by jpz4085** [comment]
Here's what I've tested and been able to determine so far:

I have tested BCD-SYS on VirtualBox with the following configuration.

- Debian Bookworm 12.5.0 GNOME Desktop
- Linux bookworm 6.1.0-21-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
- Windows 10 Professional: Major Version: 10 Minor Version: 0 Build: 19045

Performed standard Debian installation of current version with defaults and only requirements for BCD-SYS.
All packages and configuration performed under root account.
Partitions were mounted using GNOME then again manually at /mnt.
No problems running the script under root and Windows booted successfully.
No identifiable issues with this configuration.

> Here is a zip with the BCD file you asked for:

The attached recovery BCD hive is completly empty containing nothing but zeros. Even the reg file header and storage root blocks present by default in the BCD-NEW template are missing. Seems as if the file was overwritten with null data. Can't say why at this point.

> Remove entry at {cf4ca6b0-57e3-46f1-85ed-e8a96bd010e6}
> Remove {cf4ca6b0-57e3-46f1-85ed-e8a96bd010e6} from WBM display order.
> Remove entry at {d32da8ce-d3d7-4017-a889-79e9afc61bcf}
> Remove {d32da8ce-d3d7-4017-a889-79e9afc61bcf} from WBM resume object.

The verbose output quoted above indicates that the script may have been run more than once on that machine or there were already entries for the target Windows installation in the existing BCD. The script will remove them to avoid duplicates. Can you tell me more about this situation?

Also, is this issue specific to one particular computer from this environment?

**Comment by scorchpc** [comment]
I figured the empty file was the issue as well. 

We are trying to help a customer to automate their process for imaging. We have a list of images we are going through 1 by 1 to validate. The old way was Win PE and a USB drive. The new way would be Linux. 

I can have them run the script again, and this time we can erase the drive first to be extra safe.

**Comment by scorchpc** [comment]
Ok, we erased the drive, did the wim and BCD. This time we did not get a BCD error, but now it looks like this:

![image](https://github.com/jpz4085/BCD-SYS/assets/11061645/cf796493-ab7f-4469-a96e-8382c933d4cb)

And here is the \EFI\Microsoft\Recovery\BCD file

[BCD.zip](https://github.com/jpz4085/BCD-SYS/files/15278012/BCD.zip)

**Comment by jpz4085** [comment]
> And here is the \EFI\Microsoft\Recovery\BCD file

No identifiable issues with this BCD. All entries present and device data is formatted correctly.

> I can have them run the script again, and this time we can erase the drive first to be extra safe.

Exactly how is this being performed?
Is Debian, wimtools, bcd-sys and the wim file all located on a single bootable USB drive?
Is the partitioning/imaging/BCD process manual or being performed automatically by a master script?

> We are trying to help a customer to automate their process for imaging. We have a list of images we are going through > 1 by 1 to validate. The old way was Win PE and a USB drive. The new way would be Linux.

Would I be correct to assume that all these images are known to have been used recently and successfully prior to this conversion process to Linux? Are you or another person able to confirm that directly? Or is that part of this validation?
Also, are these images generalized or configured with drivers for particular hardware as well as applications?

> Ok, we erased the drive, did the wim and BCD. This time we did not get a BCD error, but now it looks like this:

The screen corruption almost looks like a video or hardware or driver issue but I couldn't say for sure.

**Comment by scorchpc** [comment]
We have an environment the unit boots to via USB. Master script performs all the steps. We use DMI to get a product name, and tie that to the WIM file that the master script utilizes. 

Yes, all of these images have been used for a long time with the prior process (Thumb drive, Win PE). I believe the images are configured for that particular hardware. 

Agree that the screen corruption looks like a video/hardware/driver issue, but it works with the previous process. Just yesterday we got a sample of a unit that does this, so hopefully we can figure out why and what to do about it. 

I wonder if wimapply has issues? Like maybe it didn't write all the files properly? 

FYI - For this project, I handle the communications with the customer and our engineering team. I am sort of a go between here. I wonder if there are some better tools / logs we could use to help debug this. I might try to persuade the senior engineer to come here and comment.

**Comment by jpz4085** [comment]
> Yes, all of these images have been used for a long time with the prior process (Thumb drive, Win PE). I believe the images are configured for that particular hardware.

OK, sounds good.

> I wonder if wimapply has issues? Like maybe it didn't write all the files properly?

That passed through my mind too. Could be worth trying the following on a test system(s) with the problematic image(s).

1. Perform all steps using the new Linux process except for BCD-SYS.
2. Boot to WinPE and use bcdboot to make bootable then check the results.

Perhaps depending on the outcome of the test the senior engineer can decide how to proceed.

**Comment by scorchpc** [comment]
FYI - When we run things manually, they seem to work. When we tried the automated environment, we had the above display issue. Having the sample in house helps!

Will keep you posted!

**Comment by scorchpc** [comment]
Here is the actual Python script we use. 
[WimDeploy.zip](https://github.com/jpz4085/BCD-SYS/files/15311045/WimDeploy.zip)

**Comment by scorchpc** [comment]
We figured out the issue with the fonts, it was due to how we were using 'wimapply'.  The font issue is a separate issue, so apologies for the extra noise on this thread, I did that because it was the same unit.  We are still investigating the BCD/boot issue, but haven't yet determined if it can be easily reproduced.

**Comment by scorchpc** [comment]
[20-61521479-BCD.zip](https://github.com/jpz4085/BCD-SYS/files/15339034/20-61521479-BCD.zip)
![20-61521479-BCD-error](https://github.com/jpz4085/BCD-SYS/assets/11061645/f1432531-cfee-4401-98a7-b5999957f5ee)

Hi Sir, 

We got the BCD boot error again. Attached is a screenshot of the error and the BCD file itself.

wiminfo:

System Root:            WINDOWS
Major Version:          10
Minor Version:          0
Build:                  17763
Service Pack Build:     3287
Service Pack Level:     0


Let me know any feedback or needs. 

Thanks again!

**Comment by jpz4085** [comment]
The attached BCD does not have any identifiable issues and is comparable to the one from the previous post (about the unrelated screen corruption) as well as a BCD made with the Microsoft tools. However it appears to be the main store and not the Recovery one referenced in the latest screenshot. I suspect the Recovery file is blank again as occurred with the original issue. You can confirm this by viewing the file with a hex viewer/editor such as xxd and it will display only zeros.

`xxd /mnt/EFI/EFI/Microsoft/Recovery/BCD`

Let me know if that is correct.

**Comment by scorchpc** [comment]
You are correct. I definitely got the wrong file. I will get back to you. Sorry again!

**Comment by scorchpc** [comment]
I am going to work on getting the correct file. 

But I was wondering, should your script check to ensure a proper file was made? And if not, then either fix it or report an error? Just a thought....

**Comment by jpz4085** [comment]
> But I was wondering, should your script check to ensure a proper file was made? And if not, then either fix it or report an error? Just a thought....

I have added checks to the BCD creation and updating process that will return an error if the stores can't be built or copied to the destination successfully. This should help with identifying the step where an issue is occurring. Also the temporary hivexsh scripts and BCD files will remain in the temp folder so they can be provided for troubleshooting.

**Comment by scorchpc** [comment]
Thank you sir, this will help!

FYI - I did get them to try this unit again, and it worked this time.

**Comment by scorchpc** [comment]
FYI - We have had many images work. We have also converted a couple of old Ghost images to WIM.

**Comment by scorchpc** [comment]
We had another Recovery\BCD error. I got the unit back, and checked the file. It seems ok. 
[22I001416T-Recovery-BCD.zip](https://github.com/user-attachments/files/15672226/22I001416T-Recovery-BCD.zip)

I then tried to run the process manually, it succeeded, but nothing ended up in the temp folder. Not sure why?

**Comment by jpz4085** [comment]
Recovery store looks fine. Was this the installed file or the one from the temp directory?

> I then tried to run the process manually, it succeeded, but nothing ended up in the temp folder. Not sure why?

The temp files will only remain if the build process or file copy to the system partition failed. They will be deleted when successful.

**Comment by scorchpc** [comment]
The installed one (from SDA2\EFI\Microsoft\Recovery\BCD). And the issue repeated. Will have him hook up to DEV tomorrow. 
 Is there any thing else we can do here?
 Any information you need? 

Ok on the temp files.

**Comment by jpz4085** [comment]
> Is there any thing else we can do here?
> Any information you need?

Not that I can see at this point. No obvious points of failure I can identify.  Seems to be an intermittent issue that's specific to the deployment environment the script is running from.

**Comment by scorchpc** [comment]
Why would we get this BCD error if the file looks fine?

it has repeated on this SN / same unit / WIM now. 

Many different units / WIMs have worked.

**Comment by scorchpc** [comment]
I guess maybe I could do the process with windows, and then compare the BCD files.

**Comment by scorchpc** [comment]
[Git.zip](https://github.com/user-attachments/files/15748700/Git.zip)

On this particular unit the Recovery\BCD error repeats, we have seen this several times now after imaging and your bcd-sys script. Yesterday, the unit was rebooted after the Recovery\BCD error, and Windows appears to have automatically fixed the file. 

Attached are the "Recovery-BCD-Issue" (when issue happens) and "Recovery-BCD-Fixed" (after reboot/automatically fixed) files.

Using "hexdump -C" on these files, we can see that this line is different:


Issue file:
00004070  b3 65 40 65 85 0b a4 39  b3 b2 e9 b9 00 00 00 00  |.e@e...9........|

Fixed file:
00004070  d9 2d 47 19 87 d1 de 45  9f fd 02 42 00 00 00 00  |.-G....E...B....|


Tracing this back using XML tools (hivexml and xmllint), we need help from you to understand the encoding of the 'Elements\11000001' value that changed and how it should correlate to disk/partition UUIDs.

Let me know any questions or needs. Thanks!

**Comment by jpz4085** [comment]
OK, this helps alot! Apparently the GUID/UUID changed for both the disk AND partition referenced in the device element for the Windows Boot Manager entry after the BCD was created.

The format of the Application Device (11000001) element is as follows:

`00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00 48 00 00 00 00 00 00 00 <partition> 00 00 00 00 <scheme> 00 00 00 <disk> 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

partition - 16 byte partition identifier
disk      - 16 byte disk identifier
scheme    - 1 byte partition scheme identifier (00 = GPT or 01 = MBR)

When using GPT the identifiers are the respective GUID/UUID of the partition and disk but when using MBR the partition identifier is the partition offset from the begining of the disk in bytes and the disk identifier is the Windows Disk Signature from the MBR. All values are hexadecimal and most are arranged in little-endian byte order. GUIDs however are stored in mixed-endian byte order with the first eight bytes in little-endian and the last eight in big-endian.[^1] Total length is 88 bytes.

This must have happened after bcd-sys finished. Are there any steps in the Python based deployment process that run after the BCDs are created that would alter this information? If so the BCDs should be created after these are complete. Perhaps as the very last process if possible.

If there are logs and/or verbose output created by the Python scripts and covering the entire process it may shed light on this situation to compare them between two similar systems. One which was successful and one which failed. Assuming this hasn't been done already.

[^1]: Added this detail for GUID byte order I had not previously mentioned.

**Comment by scorchpc** [comment]
I think we can close this.

It seems the unit we were trying is a bit flaky. It also seems to work better if we erase the drive first, not sure why, but in the full process that is what we do. 

We'll continue testing and going more units, if anything comes up, I will let you know.

Thanks again!
